apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-test3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-test3
    app.kubernetes.io/part-of: my-test3
  name: my-test3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-test3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: my-test3
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/mkosiarc-tenant/my-test3/my-test3@sha256:78b98d4c248b25718bcdcbc76e8d6e5ba0ea0a19cf47fc9471a53adb6f530ea1
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
